// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySweetShop.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MySweetShop.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202201406_AddBlockedUntilToEmailVerificationCodes")]
    partial class AddBlockedUntilToEmailVerificationCodes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MySweetShop.Api.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Десерты"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Мужские торты"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Женские торты"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Детские торты"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Свадебные торты"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Наборы"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Напитки"
                        });
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.EmailChangeCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("NewEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("EmailChangeCodes");
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.EmailVerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("BlockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("EmailVerificationCodes");
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa1111-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Миндальный бисквит + хрустящий слой + начинка из вишни и малины + фисташковый мусс",
                            ImageUrl = "/SeedImages/Desserts/cherry_pistachio.webp",
                            Name = "Вишня-фисташка",
                            Price = 500m
                        },
                        new
                        {
                            Id = new Guid("aaaa1112-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Шоколадный бисквит + хрустящий слой + ганаш + шоколадный мусс",
                            ImageUrl = "/SeedImages/Desserts/two_chocolates.webp",
                            Name = "Два шоколада",
                            Price = 480m
                        },
                        new
                        {
                            Id = new Guid("aaaa1113-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Бисквит из грецкого ореха + крем с сыром дорблю + начинка из груши + мусс с белым шоколадом",
                            ImageUrl = "/SeedImages/Desserts/door_blue_walnut.webp",
                            Name = "Дорблю-грецкий орех",
                            Price = 520m
                        },
                        new
                        {
                            Id = new Guid("aaaa1114-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Шоколадный брауни + креме с молочным шоколадом + мусс с манго и маракуйей",
                            ImageUrl = "/SeedImages/Desserts/mango_chocolate_passion_fruit.webp",
                            Name = "Манго-шоколад-маракуйя",
                            Price = 550m
                        },
                        new
                        {
                            Id = new Guid("aaaa1115-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Авторский Наполеон с нежным сливочным кремом на белом бельгийском шоколаде",
                            ImageUrl = "/SeedImages/Desserts/napoleon.jpg",
                            Name = "Наполеон",
                            Price = 400m
                        },
                        new
                        {
                            Id = new Guid("aaaa1116-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Основа из песочного печенья + крем чиз с добавлением смородины + смородина в украшении сверху",
                            ImageUrl = "/SeedImages/Desserts/blackcurrant_cheesecake.jpg",
                            Name = "Чизкейк чёрная смородина",
                            Price = 450m
                        },
                        new
                        {
                            Id = new Guid("aaaa1117-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Бисквит красный бархат + хрустящий слой + йогуртовый мусс",
                            ImageUrl = "/SeedImages/Desserts/red_velvet.webp",
                            Name = "Красный бархат",
                            Price = 470m
                        },
                        new
                        {
                            Id = new Guid("aaaa1118-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Нежнейшее безе + взбитые сливки + ягоды по сезону",
                            ImageUrl = "/SeedImages/Desserts/pavlova.jpg",
                            Name = "Павлова",
                            Price = 490m
                        },
                        new
                        {
                            Id = new Guid("aaaa1119-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Миндальный тарт + солёная карамель + микс орехов",
                            ImageUrl = "/SeedImages/Desserts/cake_with_nuts.jpg",
                            Name = "Тарт с орехами",
                            Price = 460m
                        },
                        new
                        {
                            Id = new Guid("aaaa1120-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Миндальный тарт + крем чиз + ягоды",
                            ImageUrl = "/SeedImages/Desserts/cake_with_berries.jpg",
                            Name = "Тарт с ягодами",
                            Price = 460m
                        },
                        new
                        {
                            Id = new Guid("aaaa1121-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Хрустящая трубочка + нежный крем с солёной карамелью",
                            ImageUrl = "/SeedImages/Desserts/straw.jpg",
                            Name = "Трубочка",
                            Price = 320m
                        },
                        new
                        {
                            Id = new Guid("aaaa1122-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Вкус: Ванильная, Шоколадкая, Фисташковая",
                            ImageUrl = "/SeedImages/Desserts/potatoes.jpg",
                            Name = "Картошка в ассортименте",
                            Price = 280m
                        },
                        new
                        {
                            Id = new Guid("aaaa1123-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Нежнейший эклер с заварным кремом. Вкус: Ванильный, Шоколадный, Карамельный, Фисташковый",
                            ImageUrl = "/SeedImages/Desserts/eclair.jpg",
                            Name = "Эклер в ассортименте",
                            Price = 300m
                        },
                        new
                        {
                            Id = new Guid("aaaa1124-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Три вида орехов с воздушными рисовыми шариками, хрустящей вафлей в бельгийском шоколаде",
                            ImageUrl = "/SeedImages/Desserts/no_image.png",
                            Name = "Батончик ореховый",
                            Price = 200m
                        },
                        new
                        {
                            Id = new Guid("aaaa1125-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageUrl = "/SeedImages/Desserts/macaron.webp",
                            Name = "Макарон в ассортименте",
                            Price = 250m
                        },
                        new
                        {
                            Id = new Guid("aaaa1126-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageUrl = "/SeedImages/Desserts/no_image.png",
                            Name = "Ириска",
                            Price = 150m
                        },
                        new
                        {
                            Id = new Guid("aaaa1127-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageUrl = "/SeedImages/Desserts/donut.jpg",
                            Name = "Пончик",
                            Price = 120m
                        },
                        new
                        {
                            Id = new Guid("aaaa1128-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ImageUrl = "/SeedImages/Desserts/esterhazy.jpg",
                            Name = "Эстерхази",
                            Price = 480m
                        },
                        new
                        {
                            Id = new Guid("bbbb1111-bbbb-1111-bbbb-bbbbbbbbbbbb"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Начинки муссовых тортов: Зайкина радость, Новый медовик, Бейлиз, Два шоколада, Шоколад-манго-маракуйя, Клубника-персик-сливки, Груша-карамель, Фундук-карамель, Вишнёвый или клубничный йогурт",
                            ImageUrl = "/SeedImages/MaleCakes/m_mousse_cake.jpg",
                            Name = "Муссовый торт",
                            Price = 2500m
                        },
                        new
                        {
                            Id = new Guid("bbbb1112-bbbb-1111-bbbb-bbbbbbbbbbbb"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            ImageUrl = "/SeedImages/MaleCakes/m_sponge_cake.jpg",
                            Name = "Бисквитный торт",
                            Price = 2000m
                        },
                        new
                        {
                            Id = new Guid("cccc1111-cccc-1111-cccc-cccccccccccc"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Начинки муссовых тортов: Зайкина радость, Новый медовик, Бейлиз, Два шоколада, Шоколад-манго-маракуйя, Клубника-персик-сливки, Груша-карамель, Фундук-карамель, Вишнёвый или клубничный йогурт",
                            ImageUrl = "/SeedImages/FemaleCakes/w_mousse_cake.jpg",
                            Name = "Муссовый торт",
                            Price = 2500m
                        },
                        new
                        {
                            Id = new Guid("cccc1112-cccc-1111-cccc-cccccccccccc"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            ImageUrl = "/SeedImages/FemaleCakes/w_sponge_cake.jpg",
                            Name = "Бисквитный торт",
                            Price = 2000m
                        },
                        new
                        {
                            Id = new Guid("dddd1111-dddd-1111-dddd-dddddddddddd"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Начинки муссовых тортов: Зайкина радость, Новый медовик, Бейлиз, Два шоколада, Шоколад-манго-маракуйя, Клубника-персик-сливки, Груша-карамель, Фундук-карамель, Вишнёвый или клубничный йогурт",
                            ImageUrl = "/SeedImages/KidsCakes/c_mousse_cake.jpg",
                            Name = "Муссовый торт",
                            Price = 2500m
                        },
                        new
                        {
                            Id = new Guid("dddd1112-dddd-1111-dddd-dddddddddddd"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            ImageUrl = "/SeedImages/KidsCakes/c_sponge_cake.jpg",
                            Name = "Бисквитный торт",
                            Price = 2000m
                        },
                        new
                        {
                            Id = new Guid("eeee1111-eeee-1111-eeee-eeeeeeeeeeee"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            ImageUrl = "/SeedImages/WeddingCakes/wedding_cake_with_two_tiers.webp",
                            Name = "Свадебный торт 2 яруса",
                            Price = 6000m
                        },
                        new
                        {
                            Id = new Guid("eeee1112-eeee-1111-eeee-eeeeeeeeeeee"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            ImageUrl = "/SeedImages/WeddingCakes/wedding_cake_has_three_tiers.webp",
                            Name = "Свадебный торт 3 яруса",
                            Price = 7500m
                        },
                        new
                        {
                            Id = new Guid("eeee1113-eeee-1111-eeee-eeeeeeeeeeee"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            ImageUrl = "/SeedImages/WeddingCakes/wedding_cake_cupcakes.webp",
                            Name = "Свадебный торт + капкейки",
                            Price = 8000m
                        },
                        new
                        {
                            Id = new Guid("ffff1111-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            ImageUrl = "/SeedImages/Sets/truffle_9pcs.jpg",
                            Name = "Трюфель 9шт",
                            Price = 1200m
                        },
                        new
                        {
                            Id = new Guid("ffff1112-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "4 любых пирожных на ваш выбор в одном наборе",
                            ImageUrl = "/SeedImages/Sets/assorted_4_cakes.jpg",
                            Name = "Ассорти из 4-х пирожных",
                            Price = 1000m
                        },
                        new
                        {
                            Id = new Guid("ffff1113-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Макарон в ассортименте и свежие цветы",
                            ImageUrl = "/SeedImages/Sets/pieces_4_of_pasta_flowers.webp",
                            Name = "Макарон 4шт + цветы",
                            Price = 900m
                        },
                        new
                        {
                            Id = new Guid("ffff1114-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Макарон 6шт в ассортименте и свежайшие цветы",
                            ImageUrl = "/SeedImages/Sets/pieces_6_of_pasta_flowers.jpg",
                            Name = "Макарон 6шт + цветы",
                            Price = 1300m
                        },
                        new
                        {
                            Id = new Guid("ffff1115-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Макарон и зефир в ассортименте и цветы на выбор",
                            ImageUrl = "/SeedImages/Sets/pcs6_macaroni_9pcs_marshmallows_flowers.jpg",
                            Name = "Макарон 6шт + зефир 9шт + цветы",
                            Price = 1500m
                        },
                        new
                        {
                            Id = new Guid("ffff1116-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Макарон в ассортименте + вкуснейший зефир + цветы",
                            ImageUrl = "/SeedImages/Sets/pcs8_macaroni_8pcs_marshmallows_flowers.webp",
                            Name = "Макарон 8шт + зефир 8шт + цветы",
                            Price = 1600m
                        },
                        new
                        {
                            Id = new Guid("ffff1117-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Внешний вид может отличаться",
                            ImageUrl = "/SeedImages/Sets/pcs_4_cupcake.jpg",
                            Name = "Капкейк 4шт",
                            Price = 800m
                        },
                        new
                        {
                            Id = new Guid("ffff1118-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            ImageUrl = "/SeedImages/Sets/pcs6_cupcakes.jpg",
                            Name = "Капкейки 6шт",
                            Price = 1200m
                        },
                        new
                        {
                            Id = new Guid("ffff1119-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Внешний вид может отличаться",
                            ImageUrl = "/SeedImages/Sets/pcs9_cupcakes_6pcs_pasta.jpg",
                            Name = "Капкейки 9шт + макарон 6шт",
                            Price = 1800m
                        },
                        new
                        {
                            Id = new Guid("ffff1120-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Внешний вид может отличаться",
                            ImageUrl = "/SeedImages/Sets/cupcake_12pcs.jpg",
                            Name = "Капкейк 12шт",
                            Price = 2400m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111111"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/espresso.jpg",
                            Name = "Эспрессо 30 мл.",
                            Price = 150m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111112"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/espresso.jpg",
                            Name = "Двойной эспрессо",
                            Price = 200m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111113"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/latte.jpg",
                            Name = "Американо 130 мл.",
                            Price = 180m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111114"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/americano.jpg",
                            Name = "Капучино 250/300 мл.",
                            Price = 250m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111115"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/americano.jpg",
                            Name = "Латте 250/300 мл.",
                            Price = 270m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111116"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/americano.jpg",
                            Name = "Латте макиато 250/300 мл.",
                            Price = 150m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111117"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/americano.jpg",
                            Name = "Флэт Уайт 250/300 мл.",
                            Price = 200m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111118"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/americano.jpg",
                            Name = "Чай в ассортименте 350 мл.",
                            Price = 180m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111119"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Свежевыжатый сок апельсина или грейпфрута",
                            ImageUrl = "/SeedImages/Drinks/fresh.webp",
                            Name = "Фреш 300 мл.",
                            Price = 250m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111120"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/milkshake.webp",
                            Name = "Молочный коктейль 350 мл.",
                            Price = 270m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111121"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/hot_chocolate.png",
                            Name = "Горячий шоколад 250 мл.",
                            Price = 270m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111122"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/juice.webp",
                            Name = "Сок с трубочкой 300 мл.",
                            Price = 150m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111123"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/good_orange.webp",
                            Name = "Добрый апельсин 300 мл.",
                            Price = 200m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111124"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/good_cola.webp",
                            Name = "Добрый кола 300 мл.",
                            Price = 180m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111125"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/sprite.jpg",
                            Name = "Спрайт 500 мл.",
                            Price = 250m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111126"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/pulpy.png",
                            Name = "Pulpy 500 мл.",
                            Price = 270m
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111127"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            ImageUrl = "/SeedImages/Drinks/bonaqua.webp",
                            Name = "BonAqua 500 мл.",
                            Price = 270m
                        });
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.Product", b =>
                {
                    b.HasOne("MySweetShop.Api.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UserFavorite", b =>
                {
                    b.HasOne("MySweetShop.Api.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySweetShop.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
