// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySweetShop.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MySweetShop.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309155226_UpdateUserCooldownField")]
    partial class UpdateUserCooldownField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MySweetShop.Api.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Десерты"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Мужские торты"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Женские торты"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Детские торты"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Свадебные торты"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Наборы"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Напитки"
                        });
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.EmailChangeCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("NewEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("EmailChangeCodes");
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.EmailVerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("BlockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("EmailVerificationCodes");
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageKey")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa1111-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Миндальный бисквит + хрустящий слой + начинка из вишни и малины + фисташковый мусс",
                            Name = "Вишня-фисташка"
                        },
                        new
                        {
                            Id = new Guid("aaaa1112-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Шоколадный бисквит + хрустящий слой + ганаш + шоколадный мусс",
                            Name = "Два шоколада"
                        },
                        new
                        {
                            Id = new Guid("aaaa1113-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Бисквит из грецкого ореха + крем с сыром дорблю + начинка из груши + мусс с белым шоколадом",
                            Name = "Дорблю-грецкий орех"
                        },
                        new
                        {
                            Id = new Guid("aaaa1114-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Шоколадный брауни + креме с молочным шоколадом + мусс с манго и маракуйей",
                            Name = "Манго-шоколад-маракуйя"
                        },
                        new
                        {
                            Id = new Guid("aaaa1115-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Авторский Наполеон с нежным сливочным кремом на белом бельгийском шоколаде",
                            Name = "Наполеон"
                        },
                        new
                        {
                            Id = new Guid("aaaa1116-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Основа из песочного печенья + крем чиз с добавлением смородины + смородина в украшении сверху",
                            Name = "Чизкейк чёрная смородина"
                        },
                        new
                        {
                            Id = new Guid("aaaa1117-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Бисквит красный бархат + хрустящий слой + йогуртовый мусс",
                            Name = "Красный бархат"
                        },
                        new
                        {
                            Id = new Guid("aaaa1118-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Нежнейшее безе + взбитые сливки + ягоды по сезону",
                            Name = "Павлова"
                        },
                        new
                        {
                            Id = new Guid("aaaa1119-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Миндальный тарт + солёная карамель + микс орехов",
                            Name = "Тарт с орехами"
                        },
                        new
                        {
                            Id = new Guid("aaaa1120-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Миндальный тарт + крем чиз + ягоды",
                            Name = "Тарт с ягодами"
                        },
                        new
                        {
                            Id = new Guid("aaaa1121-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Хрустящая трубочка + нежный крем с солёной карамелью",
                            Name = "Трубочка"
                        },
                        new
                        {
                            Id = new Guid("aaaa1122-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Вкус: Ванильная, Шоколадкая, Фисташковая",
                            Name = "Картошка в ассортименте"
                        },
                        new
                        {
                            Id = new Guid("aaaa1123-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Нежнейший эклер с заварным кремом. Вкус: Ванильный, Шоколадный, Карамельный, Фисташковый",
                            Name = "Эклер в ассортименте"
                        },
                        new
                        {
                            Id = new Guid("aaaa1124-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Три вида орехов с воздушными рисовыми шариками, хрустящей вафлей в бельгийском шоколаде",
                            Name = "Батончик ореховый"
                        },
                        new
                        {
                            Id = new Guid("aaaa1125-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Макарон в ассортименте"
                        },
                        new
                        {
                            Id = new Guid("aaaa1126-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Ириска"
                        },
                        new
                        {
                            Id = new Guid("aaaa1127-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Пончик"
                        },
                        new
                        {
                            Id = new Guid("aaaa1128-aaaa-1111-aaaa-aaaaaaaaaaaa"),
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Эстерхази"
                        },
                        new
                        {
                            Id = new Guid("bbbb1111-bbbb-1111-bbbb-bbbbbbbbbbbb"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Начинки муссовых тортов: Зайкина радость, Новый медовик, Бейлиз, Два шоколада, Шоколад-манго-маракуйя, Клубника-персик-сливки, Груша-карамель, Фундук-карамель, Вишнёвый или клубничный йогурт",
                            Name = "Муссовый торт"
                        },
                        new
                        {
                            Id = new Guid("bbbb1112-bbbb-1111-bbbb-bbbbbbbbbbbb"),
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            Name = "Бисквитный торт"
                        },
                        new
                        {
                            Id = new Guid("cccc1111-cccc-1111-cccc-cccccccccccc"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Начинки муссовых тортов: Зайкина радость, Новый медовик, Бейлиз, Два шоколада, Шоколад-манго-маракуйя, Клубника-персик-сливки, Груша-карамель, Фундук-карамель, Вишнёвый или клубничный йогурт",
                            Name = "Муссовый торт"
                        },
                        new
                        {
                            Id = new Guid("cccc1112-cccc-1111-cccc-cccccccccccc"),
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            Name = "Бисквитный торт"
                        },
                        new
                        {
                            Id = new Guid("dddd1111-dddd-1111-dddd-dddddddddddd"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Начинки муссовых тортов: Зайкина радость, Новый медовик, Бейлиз, Два шоколада, Шоколад-манго-маракуйя, Клубника-персик-сливки, Груша-карамель, Фундук-карамель, Вишнёвый или клубничный йогурт",
                            Name = "Муссовый торт"
                        },
                        new
                        {
                            Id = new Guid("dddd1112-dddd-1111-dddd-dddddddddddd"),
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            Name = "Бисквитный торт"
                        },
                        new
                        {
                            Id = new Guid("eeee1111-eeee-1111-eeee-eeeeeeeeeeee"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            Name = "Свадебный торт 2 яруса"
                        },
                        new
                        {
                            Id = new Guid("eeee1112-eeee-1111-eeee-eeeeeeeeeeee"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            Name = "Свадебный торт 3 яруса"
                        },
                        new
                        {
                            Id = new Guid("eeee1113-eeee-1111-eeee-eeeeeeeeeeee"),
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            Name = "Свадебный торт + капкейки"
                        },
                        new
                        {
                            Id = new Guid("ffff1111-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Трюфель 9шт"
                        },
                        new
                        {
                            Id = new Guid("ffff1112-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "4 любых пирожных на ваш выбор в одном наборе",
                            Name = "Ассорти из 4-х пирожных"
                        },
                        new
                        {
                            Id = new Guid("ffff1113-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Макарон в ассортименте и свежие цветы",
                            Name = "Макарон 4шт + цветы"
                        },
                        new
                        {
                            Id = new Guid("ffff1114-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Макарон 6шт в ассортименте и свежайшие цветы",
                            Name = "Макарон 6шт + цветы"
                        },
                        new
                        {
                            Id = new Guid("ffff1115-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Макарон и зефир в ассортименте и цветы на выбор",
                            Name = "Макарон 6шт + зефир 9шт + цветы"
                        },
                        new
                        {
                            Id = new Guid("ffff1116-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Макарон в ассортименте + вкуснейший зефир + цветы",
                            Name = "Макарон 8шт + зефир 8шт + цветы"
                        },
                        new
                        {
                            Id = new Guid("ffff1117-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Внешний вид может отличаться",
                            Name = "Капкейк 4шт"
                        },
                        new
                        {
                            Id = new Guid("ffff1118-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Капкейки 6шт"
                        },
                        new
                        {
                            Id = new Guid("ffff1119-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Внешний вид может отличаться",
                            Name = "Капкейки 9шт + макарон 6шт"
                        },
                        new
                        {
                            Id = new Guid("ffff1120-ffff-1111-ffff-ffffffffffff"),
                            CategoryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Внешний вид может отличаться",
                            Name = "Капкейк 12шт"
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111111"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Эспрессо 30 мл."
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111112"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Двойной эспрессо"
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111113"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Американо 130 мл."
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111114"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Капучино 250/300 мл."
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111115"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Латте 250/300 мл."
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111116"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Латте макиато 250/300 мл."
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111117"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Флэт Уайт 250/300 мл."
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111118"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Чай в ассортименте 350 мл."
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111119"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Свежевыжатый сок апельсина или грейпфрута",
                            Name = "Фреш 300 мл."
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111120"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Молочный коктейль 350 мл."
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111121"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Горячий шоколад 250 мл."
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111122"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Сок с трубочкой 300 мл."
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111123"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Добрый апельсин 300 мл."
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111124"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Добрый кола 300 мл."
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111125"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Спрайт 500 мл."
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111126"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Pulpy 500 мл."
                        },
                        new
                        {
                            Id = new Guid("88888888-1111-1111-8888-111111111127"),
                            CategoryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "BonAqua 500 мл."
                        });
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastProfileUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.Product", b =>
                {
                    b.HasOne("MySweetShop.Api.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("MySweetShop.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserFavorite", b =>
                {
                    b.HasOne("MySweetShop.Api.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySweetShop.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
