// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySweetShop.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MySweetShop.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260131144309_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MySweetShop.Api.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            Name = "Десерты"
                        },
                        new
                        {
                            Id = new Guid("59f62526-63d1-448e-86e3-c37aa0214d64"),
                            Name = "Мужские торты"
                        },
                        new
                        {
                            Id = new Guid("5a88b88d-bdb3-4286-b426-0c63a4f0ca79"),
                            Name = "Женские торты"
                        },
                        new
                        {
                            Id = new Guid("9b212ba2-45ca-4d17-b327-279ee3f6bfca"),
                            Name = "Детские торты"
                        },
                        new
                        {
                            Id = new Guid("88c4f058-26eb-40b7-bce6-e1e9e249b7a3"),
                            Name = "Свадебные торты"
                        },
                        new
                        {
                            Id = new Guid("d6619797-6f1b-45c8-9ba2-653f03a1ef37"),
                            Name = "Наборы"
                        },
                        new
                        {
                            Id = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            Name = "Напитки"
                        });
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.EmailChangeCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("NewEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("EmailChangeCodes");
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.EmailVerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("EmailVerificationCodes");
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39265bc0-da28-44cc-93f7-67f688e8642c"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            Description = "Миндальный бисквит + хрустящий слой + начинка из вишни и малины + фисташковый мусс",
                            ImageUrl = "/SeedImages/Desserts/cherry_pistachio.jpeg",
                            Name = "Вишня-фисташка",
                            Price = 500m
                        },
                        new
                        {
                            Id = new Guid("1a8de910-ed4f-412b-82ae-d64e946b24a6"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            Description = "Шоколадный бисквит + хрустящий слой + ганаш + шоколадный мусс",
                            ImageUrl = "/SeedImages/Desserts/two_chocolates.jpeg",
                            Name = "Два шоколада",
                            Price = 480m
                        },
                        new
                        {
                            Id = new Guid("0928c0ce-06e4-4381-88e0-637e6780cf29"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            Description = "Бисквит из грецкого ореха + крем с сыром дорблю + начинка из груши + мусс с белым шоколадом",
                            ImageUrl = "/SeedImages/Desserts/door_blue_walnut.jpeg",
                            Name = "Дорблю-грецкий орех",
                            Price = 520m
                        },
                        new
                        {
                            Id = new Guid("a420f339-36f8-4486-a6da-98ec7fd8cb99"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            Description = "Шоколадный брауни + креме с молочным шоколадом + мусс с манго и маракуйей",
                            ImageUrl = "/SeedImages/Desserts/mango_chocolate_passion_fruit.jpeg",
                            Name = "Манго-шоколад-маракуйя",
                            Price = 550m
                        },
                        new
                        {
                            Id = new Guid("3d7ca1c1-36a0-4c98-86ff-9032725ee57d"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            Description = "Авторский Наполеон с нежным сливочным кремом на белом бельгийском шоколаде",
                            ImageUrl = "/SeedImages/Desserts/napoleon.jpg",
                            Name = "Наполеон",
                            Price = 400m
                        },
                        new
                        {
                            Id = new Guid("2a7d4cf1-5ea2-4181-bd3a-8c38029b9b3c"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            Description = "Основа из песочного печенья + крем чиз с добавлением смородины + смородина в украшении сверху",
                            ImageUrl = "/SeedImages/Desserts/blackcurrant_cheesecake.jpg",
                            Name = "Чизкейк чёрная смородина",
                            Price = 450m
                        },
                        new
                        {
                            Id = new Guid("abfabb8d-da45-46f6-b9c0-90ef499939b1"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            Description = "Бисквит красный бархат + хрустящий слой + йогуртовый мусс",
                            ImageUrl = "/SeedImages/Desserts/red_velvet.jpeg",
                            Name = "Красный бархат",
                            Price = 470m
                        },
                        new
                        {
                            Id = new Guid("599c837c-2a3f-4856-b94e-85a9e019f27c"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            Description = "Нежнейшее безе + взбитые сливки + ягоды по сезону",
                            ImageUrl = "/SeedImages/Desserts/pavlova.jpg",
                            Name = "Павлова",
                            Price = 490m
                        },
                        new
                        {
                            Id = new Guid("9f17bafc-c96d-452f-833c-b3ca88d76e62"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            Description = "Миндальный тарт + солёная карамель + микс орехов",
                            ImageUrl = "/SeedImages/Desserts/cake_with_nuts.jpg",
                            Name = "Тарт с орехами",
                            Price = 460m
                        },
                        new
                        {
                            Id = new Guid("55cd13ee-e572-4c85-86b7-5cb3632cfeb7"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            Description = "Миндальный тарт + крем чиз + ягоды",
                            ImageUrl = "/SeedImages/Desserts/cake_with_berries.jpg",
                            Name = "Тарт с ягодами",
                            Price = 460m
                        },
                        new
                        {
                            Id = new Guid("d14b8fb8-753f-49db-972c-c0cc871ef01f"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            Description = "Хрустящая трубочка + нежный крем с солёной карамелью",
                            ImageUrl = "/SeedImages/Desserts/straw.jpg",
                            Name = "Трубочка",
                            Price = 320m
                        },
                        new
                        {
                            Id = new Guid("5a61abd6-3eb1-4fac-b811-71c91a89f3cc"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            Description = "Вкус: Ванильная, Шоколадкая, Фисташковая",
                            ImageUrl = "/SeedImages/Desserts/potatoes.jpg",
                            Name = "Картошка в ассортименте",
                            Price = 280m
                        },
                        new
                        {
                            Id = new Guid("8a7c1027-4dde-4924-b36c-3a8c94bca3fe"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            Description = "Нежнейший эклер с заварным кремом. Вкус: Ванильный, Шоколадный, Карамельный, Фисташковый",
                            ImageUrl = "/SeedImages/Desserts/eclair.jpg",
                            Name = "Эклер в ассортименте",
                            Price = 300m
                        },
                        new
                        {
                            Id = new Guid("1e2b7ea9-d412-4f96-962c-fc9c5889735d"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            Description = "Три вида орехов с воздушными рисовыми шариками, хрустящей вафлей в бельгийском шоколаде",
                            ImageUrl = "/SeedImages/Desserts/no_image.png",
                            Name = "Батончик ореховый",
                            Price = 200m
                        },
                        new
                        {
                            Id = new Guid("80bec1aa-7bb1-4aa5-9c90-6cc06f0aaff6"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            ImageUrl = "/SeedImages/Desserts/macaron.jpeg",
                            Name = "Макарон в ассортименте",
                            Price = 250m
                        },
                        new
                        {
                            Id = new Guid("798a5085-bd6f-4bfc-a390-b9cf4ddc21fe"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            ImageUrl = "/SeedImages/Desserts/no_image.png",
                            Name = "Ириска",
                            Price = 150m
                        },
                        new
                        {
                            Id = new Guid("230df748-3ddd-4dc1-9320-7bd1284fea91"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            ImageUrl = "/SeedImages/Desserts/donut.jpg",
                            Name = "Пончик",
                            Price = 120m
                        },
                        new
                        {
                            Id = new Guid("f1eef214-5522-46f1-9216-fde6094fd7a0"),
                            CategoryId = new Guid("a56b0d31-28c5-4ed6-873c-3c9cc857691a"),
                            ImageUrl = "/SeedImages/Desserts/esterhazy.jpg",
                            Name = "Эстерхази",
                            Price = 480m
                        },
                        new
                        {
                            Id = new Guid("d9e16f9d-80dc-4967-a2cc-8bb2e5d8a56d"),
                            CategoryId = new Guid("59f62526-63d1-448e-86e3-c37aa0214d64"),
                            Description = "Начинки муссовых тортов: Зайкина радость, Новый медовик, Бейлиз, Два шоколада, Шоколад-манго-маракуйя, Клубника-персик-сливки, Груша-карамель, Фундук-карамель, Вишнёвый или клубничный йогурт",
                            ImageUrl = "/SeedImages/MaleCakes/m_mousse_cake.jpg",
                            Name = "Муссовый торт",
                            Price = 2500m
                        },
                        new
                        {
                            Id = new Guid("44439eb4-a693-4f1e-a866-1eb1192a8f8d"),
                            CategoryId = new Guid("59f62526-63d1-448e-86e3-c37aa0214d64"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            ImageUrl = "/SeedImages/MaleCakes/m_sponge_cake.jpg",
                            Name = "Бисквитный торт",
                            Price = 2000m
                        },
                        new
                        {
                            Id = new Guid("fe7be9d0-4f53-4af4-8a8b-7ccde9b7ea2b"),
                            CategoryId = new Guid("5a88b88d-bdb3-4286-b426-0c63a4f0ca79"),
                            Description = "Начинки муссовых тортов: Зайкина радость, Новый медовик, Бейлиз, Два шоколада, Шоколад-манго-маракуйя, Клубника-персик-сливки, Груша-карамель, Фундук-карамель, Вишнёвый или клубничный йогурт",
                            ImageUrl = "/SeedImages/FemaleCakes/w_mousse_cake.jpg",
                            Name = "Муссовый торт",
                            Price = 2500m
                        },
                        new
                        {
                            Id = new Guid("94320477-c17a-44ad-a46a-a7ef184ac0a5"),
                            CategoryId = new Guid("5a88b88d-bdb3-4286-b426-0c63a4f0ca79"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            ImageUrl = "/SeedImages/FemaleCakes/w_sponge_cake.jpg",
                            Name = "Бисквитный торт",
                            Price = 2000m
                        },
                        new
                        {
                            Id = new Guid("7ad095bb-12ca-49b8-87c2-f49639668e8b"),
                            CategoryId = new Guid("9b212ba2-45ca-4d17-b327-279ee3f6bfca"),
                            Description = "Начинки муссовых тортов: Зайкина радость, Новый медовик, Бейлиз, Два шоколада, Шоколад-манго-маракуйя, Клубника-персик-сливки, Груша-карамель, Фундук-карамель, Вишнёвый или клубничный йогурт",
                            ImageUrl = "/SeedImages/KidsCakes/c_mousse_cake.jpg",
                            Name = "Муссовый торт",
                            Price = 2500m
                        },
                        new
                        {
                            Id = new Guid("2a3addcb-cf42-4d42-9f1c-d19a9bc62adb"),
                            CategoryId = new Guid("9b212ba2-45ca-4d17-b327-279ee3f6bfca"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            ImageUrl = "/SeedImages/KidsCakes/c_sponge_cake.jpg",
                            Name = "Бисквитный торт",
                            Price = 2000m
                        },
                        new
                        {
                            Id = new Guid("3d047e04-0319-4d0a-8cd1-6887c27b585c"),
                            CategoryId = new Guid("88c4f058-26eb-40b7-bce6-e1e9e249b7a3"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            ImageUrl = "/SeedImages/WeddingCakes/wedding_cake_with_two_tiers.jpeg",
                            Name = "Свадебный торт 2 яруса",
                            Price = 6000m
                        },
                        new
                        {
                            Id = new Guid("6c29aef2-bac2-4261-8ec6-953052b20974"),
                            CategoryId = new Guid("88c4f058-26eb-40b7-bce6-e1e9e249b7a3"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            ImageUrl = "/SeedImages/WeddingCakes/wedding_cake_has_three_tiers.jpeg",
                            Name = "Свадебный торт 3 яруса",
                            Price = 7500m
                        },
                        new
                        {
                            Id = new Guid("8365e5ef-5d8b-4607-b8a8-c0ffb27e390b"),
                            CategoryId = new Guid("88c4f058-26eb-40b7-bce6-e1e9e249b7a3"),
                            Description = "Начинки бисквитных тортов: Фруктовый, Красный бархат, Сникерс, Рафаэлло",
                            ImageUrl = "/SeedImages/WeddingCakes/wedding_cake_cupcakes.jpeg",
                            Name = "Свадебный торт + капкейки",
                            Price = 8000m
                        },
                        new
                        {
                            Id = new Guid("80057b8c-fb1d-4b3b-97fa-96b2c74f0452"),
                            CategoryId = new Guid("d6619797-6f1b-45c8-9ba2-653f03a1ef37"),
                            ImageUrl = "/SeedImages/Sets/truffle_9pcs.jpg",
                            Name = "Трюфель 9шт",
                            Price = 1200m
                        },
                        new
                        {
                            Id = new Guid("52d9f701-1deb-41b8-9b50-c0d3a6380f87"),
                            CategoryId = new Guid("d6619797-6f1b-45c8-9ba2-653f03a1ef37"),
                            Description = "4 любых пирожных на ваш выбор в одном наборе",
                            ImageUrl = "/SeedImages/Sets/assorted_4_cakes.jpg",
                            Name = "Ассорти из 4-х пирожных",
                            Price = 1000m
                        },
                        new
                        {
                            Id = new Guid("4f2ecf76-1d2a-4984-ae0d-fd91bbc9480f"),
                            CategoryId = new Guid("d6619797-6f1b-45c8-9ba2-653f03a1ef37"),
                            Description = "Макарон в ассортименте и свежие цветы",
                            ImageUrl = "/SeedImages/Sets/pieces_4_of_pasta_flowers.jpeg",
                            Name = "Макарон 4шт + цветы",
                            Price = 900m
                        },
                        new
                        {
                            Id = new Guid("1d01c9c4-c5b1-4a5b-afe7-bd972c85db63"),
                            CategoryId = new Guid("d6619797-6f1b-45c8-9ba2-653f03a1ef37"),
                            Description = "Макарон 6шт в ассортименте и свежайшие цветы",
                            ImageUrl = "/SeedImages/Sets/pieces_6_of_pasta_flowers.jpg",
                            Name = "Макарон 6шт + цветы",
                            Price = 1300m
                        },
                        new
                        {
                            Id = new Guid("e56a9c41-1985-48c0-95bf-3d69c4c508f9"),
                            CategoryId = new Guid("d6619797-6f1b-45c8-9ba2-653f03a1ef37"),
                            Description = "Макарон и зефир в ассортименте и цветы на выбор",
                            ImageUrl = "/SeedImages/Sets/pcs6_macaroni_9pcs_marshmallows_flowers.jpg",
                            Name = "Макарон 6шт + зефир 9шт + цветы",
                            Price = 1500m
                        },
                        new
                        {
                            Id = new Guid("587a7fc8-780d-4ac0-bf69-ab0b858af719"),
                            CategoryId = new Guid("d6619797-6f1b-45c8-9ba2-653f03a1ef37"),
                            Description = "Макарон в ассортименте + вкуснейший зефир + цветы",
                            ImageUrl = "/SeedImages/Sets/pcs8_macaroni_8pcs_marshmallows_flowers.jpeg",
                            Name = "Макарон 8шт + зефир 8шт + цветы",
                            Price = 1600m
                        },
                        new
                        {
                            Id = new Guid("0bc88550-948d-43de-bbae-6d7611b29b50"),
                            CategoryId = new Guid("d6619797-6f1b-45c8-9ba2-653f03a1ef37"),
                            Description = "Внешний вид может отличаться",
                            ImageUrl = "/SeedImages/Sets/pcs_4_cupcake.jpg",
                            Name = "Капкейк 4шт",
                            Price = 800m
                        },
                        new
                        {
                            Id = new Guid("d1237e2b-6cb0-4d41-8e55-7577d9912ec6"),
                            CategoryId = new Guid("d6619797-6f1b-45c8-9ba2-653f03a1ef37"),
                            ImageUrl = "/SeedImages/Sets/pcs6_cupcakes.jpg",
                            Name = "Капкейки 6шт",
                            Price = 1200m
                        },
                        new
                        {
                            Id = new Guid("61983990-d51f-40eb-ac7a-5113df5ff9b0"),
                            CategoryId = new Guid("d6619797-6f1b-45c8-9ba2-653f03a1ef37"),
                            Description = "Внешний вид может отличаться",
                            ImageUrl = "/SeedImages/Sets/pcs9_cupcakes_6pcs_pasta.jpg",
                            Name = "Капкейки 9шт + макарон 6шт",
                            Price = 1800m
                        },
                        new
                        {
                            Id = new Guid("49ec7689-4c5b-494f-bacc-0e6c189d7630"),
                            CategoryId = new Guid("d6619797-6f1b-45c8-9ba2-653f03a1ef37"),
                            Description = "Внешний вид может отличаться",
                            ImageUrl = "/SeedImages/Sets/cupcake_12pcs.jpg",
                            Name = "Капкейк 12шт",
                            Price = 2400m
                        },
                        new
                        {
                            Id = new Guid("c1a920a7-825d-4838-8d48-f89c489a5343"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/espresso.jpg",
                            Name = "Эспрессо 30 мл.",
                            Price = 150m
                        },
                        new
                        {
                            Id = new Guid("ade06f3c-9e1d-4129-b813-22ed21a445b4"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/espresso.jpg",
                            Name = "Двойной эспрессо",
                            Price = 200m
                        },
                        new
                        {
                            Id = new Guid("9c790c9b-dbe7-4e40-b069-ac092a754c0f"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/latte.jpg",
                            Name = "Американо 130 мл.",
                            Price = 180m
                        },
                        new
                        {
                            Id = new Guid("197c0beb-cc06-4f5c-b17c-d26e86130b81"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/americano.jpg",
                            Name = "Капучино 250/300 мл.",
                            Price = 250m
                        },
                        new
                        {
                            Id = new Guid("8b26f5d3-9fd6-475b-9876-a136bae19ba4"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/americano.jpg",
                            Name = "Латте 250/300 мл.",
                            Price = 270m
                        },
                        new
                        {
                            Id = new Guid("2880b0c5-8e26-43e3-8149-50b23fe956cc"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/americano.jpg",
                            Name = "Латте макиато 250/300 мл.",
                            Price = 150m
                        },
                        new
                        {
                            Id = new Guid("7879e98e-f4d4-4d43-b6ac-9393e4ad215e"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/americano.jpg",
                            Name = "Флэт Уайт 250/300 мл.",
                            Price = 200m
                        },
                        new
                        {
                            Id = new Guid("3cf53091-7f36-4249-af0b-47a7b76a945c"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/americano.jpg",
                            Name = "Чай в ассортименте 350 мл.",
                            Price = 180m
                        },
                        new
                        {
                            Id = new Guid("c49ac54b-e054-4f97-b94c-dd1ac1445e9e"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            Description = "Свежевыжатый сок апельсина или грейпфрута",
                            ImageUrl = "/SeedImages/Drinks/fresh.jpeg",
                            Name = "Фреш 300 мл.",
                            Price = 250m
                        },
                        new
                        {
                            Id = new Guid("aae92bee-88e7-4159-ae02-74a69a289fbd"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/milkshake.jpeg",
                            Name = "Молочный коктейль 350 мл.",
                            Price = 270m
                        },
                        new
                        {
                            Id = new Guid("b53760e1-5345-4e65-b881-8ab826300046"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/hot_chocolate.png",
                            Name = "Горячий шоколад 250 мл.",
                            Price = 270m
                        },
                        new
                        {
                            Id = new Guid("da7edcce-410d-461a-b978-c97d5df1e5f6"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/juice.jpeg",
                            Name = "Сок с трубочкой 300 мл.",
                            Price = 150m
                        },
                        new
                        {
                            Id = new Guid("d7b5e313-8b2c-4175-b252-f98852b5e5f6"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/good_orange.jpeg",
                            Name = "Добрый апельсин 300 мл.",
                            Price = 200m
                        },
                        new
                        {
                            Id = new Guid("202f916c-e07f-405d-a96b-2e719a914173"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/good_cola.jpeg",
                            Name = "Добрый кола 300 мл.",
                            Price = 180m
                        },
                        new
                        {
                            Id = new Guid("1a197f94-2036-4350-b1d3-864ca9179ccc"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/sprite.jpg",
                            Name = "Спрайт 500 мл.",
                            Price = 250m
                        },
                        new
                        {
                            Id = new Guid("6f982e19-4bde-4c0c-abc0-23c488caeb4e"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/pulpy.png",
                            Name = "Pulpy 500 мл.",
                            Price = 270m
                        },
                        new
                        {
                            Id = new Guid("a3293e44-d291-4521-984d-64aaf3def3aa"),
                            CategoryId = new Guid("f623d1e6-d01e-4865-946a-06af84847c67"),
                            ImageUrl = "/SeedImages/Drinks/bonaqua.jpeg",
                            Name = "BonAqua 500 мл.",
                            Price = 270m
                        });
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.Product", b =>
                {
                    b.HasOne("MySweetShop.Api.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UserFavorite", b =>
                {
                    b.HasOne("MySweetShop.Api.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySweetShop.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MySweetShop.Api.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
